print('Enter the name of cat 1:')
cat1 = input('> ')
print('Enter the name of cat 2:')
cat2 = input('> ')
print('Enter the name of cat 3:')
cat3 = input('> ')
print('Enter the name of cat 4:')
cat4 = input('> ')
print('Enter the name of cat 5:')
cat5 = input('> ')
print(f'{cat1}, {cat2}, {cat3}, {cat4}, and {cat5} are my cats.')
